"""fix_sessions_table_to_match_documentation

Revision ID: 0aaf9c2c1dbd
Revises: c12354605de9
Create Date: 2026-09-06 05:35:06.614685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aaf9c2c1dbd'
down_revision: Union[str, Sequence[str], None] = 'c12354605de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('token_jti', sa.String(length=255), nullable=False))
    op.add_column('sessions', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('remember_me', sa.Boolean(), nullable=False))
    op.add_column('sessions', sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_sessions_jti'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_constraint(op.f('sessions_refresh_token_key'), 'sessions', type_='unique')
    op.drop_constraint(op.f('sessions_token_key'), 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_token_jti'), 'sessions', ['token_jti'], unique=True)
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_column('sessions', 'is_active')
    op.drop_column('sessions', 'last_activity')
    op.drop_column('sessions', 'token')
    op.drop_column('sessions', 'refresh_token')
    op.drop_column('sessions', 'jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('jti', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('last_activity', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sessions_token_jti'), table_name='sessions')
    op.create_unique_constraint(op.f('sessions_token_key'), 'sessions', ['token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('sessions_refresh_token_key'), 'sessions', ['refresh_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_jti'), 'sessions', ['jti'], unique=True)
    op.alter_column('sessions', 'revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('sessions', 'last_activity_at')
    op.drop_column('sessions', 'remember_me')
    op.drop_column('sessions', 'refresh_token_hash')
    op.drop_column('sessions', 'token_jti')
    # ### end Alembic commands ###
