"""add_default_to_profiles_updated_at

Revision ID: 2b56153e23f0
Revises: fb4bdb206dc3
Create Date: 2026-09-04 12:33:34.959172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b56153e23f0'
down_revision: Union[str, Sequence[str], None] = 'fb4bdb206dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
