"""fix_profile_model_server_defaults

Revision ID: 3a138ac4b307
Revises: 46c23b2d862b
Create Date: 2026-09-06 05:45:00.673495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a138ac4b307'
down_revision: Union[str, Sequence[str], None] = '46c23b2d862b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
