"""fix_user_model_server_defaults

Revision ID: 46c23b2d862b
Revises: 0aaf9c2c1dbd
Create Date: 2026-09-06 05:42:34.494288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c23b2d862b'
down_revision: Union[str, Sequence[str], None] = '0aaf9c2c1dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
